"""Change table name from tickers to ticker_prices

Revision ID: 8e81284cb4ed
Revises: 4b999fc2178c
Create Date: 2022-04-10 19:31:29.754798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e81284cb4ed'
down_revision = '4b999fc2178c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_prices',
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', postgresql.MONEY(), nullable=True),
    sa.Column('high', postgresql.MONEY(), nullable=True),
    sa.Column('low', postgresql.MONEY(), nullable=True),
    sa.Column('close', postgresql.MONEY(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.drop_table('tickers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('open', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('close', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('timestamp', name='tickers_pkey')
    )
    op.drop_table('ticker_prices')
    # ### end Alembic commands ###
