"""testing alembic env.pyl

Revision ID: b250a14c4807
Revises: bcbb9b2d6473
Create Date: 2022-04-07 22:16:31.642726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b250a14c4807'
down_revision = 'bcbb9b2d6473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
