"""Update Book model to TickerPrice model

Revision ID: 4b999fc2178c
Revises: 9cda83a54bf0
Create Date: 2022-04-10 19:29:48.998624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b999fc2178c'
down_revision = '9cda83a54bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', postgresql.MONEY(), nullable=True),
    sa.Column('high', postgresql.MONEY(), nullable=True),
    sa.Column('low', postgresql.MONEY(), nullable=True),
    sa.Column('close', postgresql.MONEY(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('coauthor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.drop_table('tickers')
    # ### end Alembic commands ###
