version: "3.4"

services:
  database:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=exampledb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - marketdata:/var/lib/postgresql/data
  app :
    build: ./app/
    depends_on:
      - database
volumes:
  database:
    driver: local
  marketdata: {}
